plugins {
    id 'java'
    id 'jacoco'
    id 'checkstyle'
    id 'org.springframework.boot' version '3.3.3'
    id 'io.spring.dependency-management' version '1.1.6'
    id "org.sonarqube" version "6.2.0.5505"
    id 'com.adarshr.test-logger' version '4.0.0'
    id 'info.solidsoft.pitest' version '1.19.0-rc.1'
}

sonar {
    properties {
        property "sonar.projectKey", "sonata-piano"
        property "sonar.projectName", "sonata-piano"
    }
}

pitest {
    junit5PluginVersion = '1.2.2'
    threads = 4
}

checkstyle {
    toolVersion = "10.26.1"
}

tasks.withType(Checkstyle).configureEach {
    javaLauncher = javaToolchains.launcherFor {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

checkstyleMain {
    checkstyleClasspath += files("$rootDir/buildSrc/build/libs/buildSrc.jar")
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
    }
}

testlogger {
    theme 'standard'
    showExceptions true
    showStackTraces true
    showFullStackTraces false
    showCauses true
    slowThreshold 2000
    showSummary true
    showSimpleNames false
    showPassed true
    showSkipped true
    showFailed true
    showOnlySlow false
    showStandardStreams false
    showPassedStandardStreams true
    showSkippedStandardStreams true
    showFailedStandardStreams true
    logLevel 'lifecycle'
}

group = 'com.odeyalo.sonata'
version = '0.0.1-SNAPSHOT'

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

compileJava {
    options.compilerArgs << '-parameters'
}

repositories {
    mavenCentral()
    mavenLocal()

    maven {
        name = "GitHub-Packages"
        url = "https://maven.pkg.github.com/Project-Sonata/Suite"
        credentials {
            username = System.getenv("GITHUB_USERNAME")
            password = System.getenv("GITHUB_ACCESS_TOKEN")
        }
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.jetbrains:annotations:24.0.0'
    implementation 'commons-validator:commons-validator:1.8.0'
    implementation 'org.apache.commons:commons-lang3:3.12.0'
    implementation 'com.odeyalo.sonata:suite:1.0.0'
    implementation 'org.thymeleaf:thymeleaf-spring6'
    implementation 'org.flywaydb:flyway-database-postgresql'
    implementation 'org.postgresql:postgresql'

    implementation 'springdoc-openapi-starter-webflux-api:2.6.0'
    implementation 'org.springdoc:springdoc-openapi-starter-webflux-ui:2.6.0'

    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    compileOnly 'org.projectlombok:lombok'
    runtimeOnly 'org.postgresql:r2dbc-postgresql'
    annotationProcessor 'org.projectlombok:lombok'

    checkstyle "com.puppycrawl.tools:checkstyle:${checkstyle.toolVersion}"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'

    testImplementation('com.github.javafaker:javafaker:1.0.2') { exclude(module: 'org.yaml') }
    testImplementation 'org.yaml:snakeyaml:1.33'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'io.projectreactor:reactor-test'
    testImplementation 'name.bychkov:junit5-fakesmtp:1.0.1:jakarta'
    testImplementation 'org.testcontainers:postgresql'
}

tasks.named('test') {
    useJUnitPlatform()

    testLogging {
        exceptionFormat "full"
        showStandardStreams true
    }
}
