version: '3.8'

services:
  sonata-piano:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sonata-piano-image
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: 'postgres:15.2'
    container_name: piano_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5