spring.config.import=classpath:jackson-mapper.properties

spring.application.name=piano

# database access
spring.r2dbc.name=postgresql
spring.r2dbc.url=${DATABASE_URL}
spring.r2dbc.username=${DATABASE_USERNAME}
spring.r2dbc.password=${DATABASE_PASSWORD}

spring.flyway.url=${FLYWAY_DATABASE_URL}
spring.flyway.user=${DATABASE_USERNAME}
spring.flyway.password=${DATABASE_PASSWORD}

sonata.mail.username=${EMAIL_USERNAME}
sonata.mail.password=${EMAIL_PASSWORD}