name: 'Sonarqube analysis'
description: 'Run job to analys the PR with SonarQube'

inputs:
  gh_username:
    description: 'Github username to connect to Github Registry'
    required: true
  github-token:
    description: 'Github token'
    required: true
  sonar-token:
    description: 'Sonar token'
    required: true
  sonar-host-url:
    description: 'Sonar host url'
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache SonarQube packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: SonarQube Scan
      run: |
        ./gradlew --build-cache classes jacocoTestReport sonar -Dsonar.projectKey=sonata-piano \
          -Dsonar.scm.provider=git \
          -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }} \
          -Dsonar.pullrequest.key=${{ github.event.number }} \
          -Dsonar.pullrequest.branch=${{ github.ref_name }} \
          -Dsonar.pullrequest.base=master
      env:
        GITHUB_USERNAME: ${{ inputs.gh_username }}
        GITHUB_ACCESS_TOKEN: ${{ inputs.github-token }}
        SONAR_TOKEN: ${{ inputs.sonar-token }}
        SONAR_HOST_URL: ${{ inputs.sonar-host-url }}
      shell: bash
    - name: Generate Sonarqube report
      id: 'quality-gate-check'
      uses: phwt/sonarqube-quality-gate-action@v1
      with:
        sonar-project-key: sonata-piano
        sonar-host-url: ${{ inputs.sonar-host-url }}
        sonar-token: ${{ inputs.sonar-token }}
        pull-request: ${{ github.event.number }}
        disable-pr-comment: 'false'
        github-token: ${{ inputs.github-token }}
    - name: Output result
      run: |
        echo "${{ steps.quality-gate-check.outputs.project-status }}"
        echo "${{ steps.quality-gate-check.outputs.quality-gate-result }}"
      shell: bash