name: sonata-piano

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GH_USERNAME: ${{ secrets.GH_USERNAME }}
  GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}


jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          path: 'changelog'
      - name: Prepare environment
        run: pip install pyyaml
      - name: Validate new changelog file
        env:
          ALL_ADDED_FILES: ${{ steps.changed-files.outputs.added_files }}
        run: "python ci/changelog.py -a ${ALL_ADDED_FILES}"

      - name: Changelog files should not be changed
        env:
          ALL_CHANGED_AND_MODIFIED_FILES: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
          ALL_ADDED_FILES: ${{ steps.changed-files.outputs.added_files }}
        run: "python ci/changelog.py -m ${ALL_CHANGED_AND_MODIFIED_FILES} ${ALL_ADDED_FILES}"
  notify:
      runs-on: ubuntu-latest
      needs: [changelog]
      if: ${{failure() && needs.changelog.result == 'failure'}}
      steps:
        - uses: mshick/add-pr-comment@v2
          with:
            message: |
              **Changelog validation failed!**
                🌏
                !