name: changelog

on:
  pull_request:
    branches:
      - master

env:
  GH_USERNAME: ${{ secrets.GH_USERNAME }}
  GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}


jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          path: 'changelog'
      - name: Prepare environment
        run: pip install pyyaml
      - name: Validate new changelog file
        id: validate-new
        env:
          ALL_ADDED_FILES: ${{ steps.changed-files.outputs.added_files }}
        run:
          "python ci/changelog.py -a ${ALL_ADDED_FILES}"
          echo status=true >> "$GITHUB_OUTPUT"

      - name: Changelog files should not be changed
        id: changelogs-are-not-changed
        env:
          ALL_CHANGED_AND_MODIFIED_FILES: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
          ALL_ADDED_FILES: ${{ steps.changed-files.outputs.added_files }}
        run:
          "python ci/changelog.py -m ${ALL_CHANGED_AND_MODIFIED_FILES} ${ALL_ADDED_FILES}"
          echo status=true >> "$GITHUB_OUTPUT"
      - name: Get current UTC time
        id: datetime
        run: echo now=$(date -u '+%-m/%-d/%Y, %H:%M:%S (UTC+0)') >> "$GITHUB_OUTPUT"
      - name: Notify
        run:
          echo ${{steps.changelogs-are-not-changed.outputs.status}}
          echo ${{steps.validate-new.outputs.status}}


  notify-on-success:

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    needs: [ changelog ]
    if: ${{success() && needs.changelog.result == 'success'}}
    steps:
      - name: Get current UTC time
        id: datetime
        run: echo now=$(date -u '+%-m/%-d/%Y, %H:%M:%S (UTC+0)') >> "$GITHUB_OUTPUT"
      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            Changelog validation successful!
            
            ###### _updated: ${{ steps.datetime.outputs.now }}_

          message-id: changelog-${{github.event.pull_request}}
  notify-on-failure:
      runs-on: ubuntu-latest
      permissions:
        pull-requests: write
      needs: [changelog]
      if: ${{failure() && needs.changelog.result == 'failure'}}
      steps:
        - name: Get current UTC time
          id: datetime
          run: echo now=$(date -u '+%-m/%-d/%Y, %H:%M:%S (UTC+0)') >> "$GITHUB_OUTPUT"
        - uses: mshick/add-pr-comment@v2
          with:
            message-id: changelog-${{github.event.pull_request}}
            message: | 
              ## 🛑 Changelog Validation Failed

              Your pull request is missing a valid changelog entry.

              ### 📋 What’s Required?

              All pull requests **must create** the `.yaml` file with a description of the change. This helps us:

                - Track new features and bug fixes
                - Generate release notes
                - Keep users informed

              ---

              ### 🧾 Expected format (example)

              ```yaml
              sonata:
                piano:
                  enhancement:
                    - "Sonata-1: Add changelog to project"
              ```
              
              ###### _updated: ${{ steps.datetime.outputs.now }}_