name: tests

on:
  push:
    branches:
      - master

env:
  GH_USERNAME: ${{ secrets.GH_USERNAME }}
  GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}


permissions:
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run tests
        uses: ./.github/actions/tests
      - name: Cache Gradle packages
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/notifications/
          key: ${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}