name: tests-and-sonar

on:
  pull_request:
    branches:
      - master

env:
  GH_USERNAME: ${{ secrets.GH_USERNAME }}
  GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}


permissions:
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Change wrapper permissions
        run: |
            chmod +x ./gradlew
            echo 'Gradle wrapper permissions updated'
      - name: Run tests
        uses: ./.github/actions/tests
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: "build-out"
      - name: Prepare artifact for scanning
        run: |
          chmod u+wx .
          unzip -o build.zip
      - name: Run SonarQube analysis with report
        uses: ./.github/actions/sonarqube-analysis
        with:
          gh_username: ${{ secrets.GITHUB_USERNAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
