name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: SonarQube Scan
        run: |  
          ./gradlew test jacocoTestReport sonar -Dsonar.projectKey=sonata-piano \
            -Dsonar.scm.provider=git \
            -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }} \
            -Dsonar.pullrequest.key=${{ github.event.number }} \
            -Dsonar.pullrequest.branch=${{ github.ref_name }} \
            -Dsonar.pullrequest.base=master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}