name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v5.2.0
        with:
          args:
            -Dsonar.projectKey=sonata-piano
            -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}