name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GH_USERNAME: ${{ secrets.GH_USERNAME }}
  GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run tests
        run: bash run-tests.sh
      - name: Upload JaCoCo artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacocoTestReport.xml
          path: reports/jacocoTestReport.xml
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Download JaCoCo report
        uses: actions/download-artifact@v4
        with:
          name: "jacocoTestReport.xml"
      - name: SonarQube Scan
        run: |
          ./gradlew jacocoTestReport sonar -Dsonar.projectKey=sonata-piano \
            -Dsonar.coverage.jacoco.xmlReportPaths=jacocoReport.xml \
            -Dsonar.scm.provider=git \
            -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }} \
            -Dsonar.pullrequest.key=${{ github.event.number }} \
            -Dsonar.pullrequest.branch=${{ github.ref_name }} \
            -Dsonar.pullrequest.base=master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}